### ISSUE TITLE
Add category labels from usegalaxy.eu to the tools menu

### ISSUE THREAD

**Issue by torfinnnome** [usegalaxy-no/galaxyadmin#11]

**Comment by torfinnnome** [comment]
OK, I have finally added labels on test.usegalaxy.no. Please help me with checking that they all make sense.

**Comment by torfinnnome** [comment]
Modifications should be pushed here: https://github.com/usegalaxy-no/infrastructure-playbook/blob/master/env/common/files/galaxy/config/tool_conf.xml

**Comment by kjellp** [comment]
Looks good to me, and a very nice improvement!

Getting issue #2 fixed with Get/Send from/to NeLS tools at the top (Get 
most important) would really be a nice icing of the cake, and have ready 
for the first online NeLS/usegalaxy.no course 23/3 :)

K.

**Comment by ehj000** [comment]
The labels looks good, but I see that there are some tool categories that are misplaced or duplicated. Here are a few examples:

SAM/BAM MANIPULATION under Miscellaneous Tools should go under Genomic File Manipulation label, but there is a SAM/BAM category there already. This has more tools, but older versions. Ok to leave, or could tools be moved?

Statistics under Miscellaneous Tools should go under Statistics and Visualisation label, but there is a Statistics there already with different tools. Could tool from Statistics under Miscellaneous Tools be moved to Statistics under Statistics and Visualisation label?

Graph/Display Data under Miscellaneous Tools should go under Statistics and Visualisation label, but there is a Graph/Display Data there already with different tools. Could tools be moved as above?

I am not sure how to edit this as I don't understand the structure in tool_conf.xml

**Comment by torfinnnome** [comment]
> Getting issue #2 fixed with Get/Send from/to NeLS tools at the top (Get most important) would really be a nice icing of the cake, and have ready for the first online NeLS/usegalaxy.no course 23/3 :) K.

FIxed! (Permanently, I hope...)

**Comment by torfinnnome** [comment]
> The labels looks good, but I see that there are some tool categories that are misplaced or duplicated. Here are a few examples:

Great! Exactly the feedback I needed. Have updated now. Looks better?

**Comment by ehj000** [comment]
Looks better, but the SAMTOOLS under SAM/BAM seem to be an additional "sub-label". 

Don't want to be picky and I am not sure if it is worth the effort, but there are still some tool categories under Miscellaneous Tools that could be moved (e.g. Genome diversity could go under Genomic analysis and Filter and sort under Genomic File Manipulation)

Still there are many tool categories such as Apollo, Imaging, Phenotype Association, Fetch sequences/alignments and more that are duplicated (they are both under Miscellaneous Tools and elsewhere), They don't not contain the same tools both places. Maybe merging?

**Comment by torfinnnome** [comment]
Thanks. Have modified it now. (I had to synchronize the section IDs in tool_conf.xml with shed_tool_conf.xml to get rid of the duplicates.)

**Comment by torfinnnome** [comment]
Implemented in prod now. Labels can be modified here (and tools moved around): https://github.com/usegalaxy-no/infrastructure-playbook/blob/master/env/common/files/galaxy/config/tool_conf.xml
