### ISSUE TITLE
Re-index RNA STAR reference datasets for Sea Louse

### ISSUE THREAD

**Issue by kjetilkl** [usegalaxy-no/galaxyadmin#12]
Version 2.7.5b of RNA STAR (which we have installed) requires reference datasets to be indexed with version 2.7.4a or newer.
We have some old reference datasets on the "db.usegalaxy.no" server, in the directory "/srv/tmp/galay_uib_reference-data-tmp/reference_data/transcriptomes/lsal01/rnastar", that needs to be re-indexed with the new version of the tool and then added to our local CVMFS under "/cvmfs/data.usegalaxy.no/byhand/lsal01/star_index/....".

**Comment by torfinnnome** [comment]
Seems to work. I aligned, and was able to browse the results using Trackster.
