### ISSUE TITLE
NeLS data transfer fails when testing v.20.09

### ISSUE THREAD

**Issue by kjellp** [usegalaxy-no/galaxyadmin#15]
Most likely routing of the transfer job is not routed properly to local runner, but following default routing to slurm which is incorrect (trasnfer jobs known to not be properly handled when sent to slurm).

**Comment by bruggerk** [comment]
Jobs are not generally run on the test server, I am looking at that, I
will feed back once fixed. I happened during the re-deployment.
 On the plus side you can run fastqc using ehos/pulsar.

/Kim

**Comment by kjellp** [comment]
For the transfer jobs, a new type of error compared to earlier is found in the sterr (same for get and send to NeLS):
Traceback (most recent call last):
  File "/srv/galaxy/server/tools/data_source/nels_importer.py", line 137, in <module>
    download_from_nels_importer( options.json_parameter_file, options.galaxy_tool_data_dir )
  File "/srv/galaxy/server/tools/data_source/nels_importer.py", line 57, in download_from_nels_importer
    [host,username,sshKey] = get_ssh_credential(nelsId, api_url, client_key, client_secret)
  File "/srv/galaxy/server/tools/data_source/nels_importer.py", line 43, in get_ssh_credential
    raise Exception("HTTP response code=%s" % str(response.status_code))
Exception: HTTP response code=404

**Comment by bruggerk** [comment]
Looks like the nels credentials are wrong, this is unrelated to the
other error.
/Kim

**Comment by bruggerk** [comment]
the NeLS API has changed, so broken
/Kim

**Comment by bruggerk** [comment]
Had a session with kidane, they have shifted to a new way of doing authentication and has broken this. 
It is being fixed at their end

**Comment by torfinnnome** [comment]
So, can we close this issue?

**Comment by kjellp** [comment]
Yes. I did some transfer tests on both test.usegalaxy.no and usegalaxy.no. Closing it now :)
