### ISSUE TITLE
Change EDGEpro2DEseq python script (python2 to 3 issue)

### ISSUE THREAD

**Issue by ehj000** [usegalaxy-no/galaxyadmin#16]
Could someone with ssh access (I don't have it yet) please change two lines in this python script: /srv/galaxy/var/shed_tools/galaxy-ntnu.bioinfo.no/toolshed_nels/repos/kjetil/edgepro2deseq/ce665b3f5811/edgepro2deseq/edgepro/edge2deseq.py

Line 29 from:
    print '\t'.join(['gene'] + filenames)
to:
    print ('\t'.join(['gene'] + filenames))
And line 31 from:
        print '\t'.join([name] + results[name])
to:
        print ('\t'.join([name] + results[name]))

**Comment by kjetilkl** [comment]
I have updated the edgepro2deseq tool wrapper in the NeLS toolshed so the tool can be reinstalled

**Comment by ehj000** [comment]
I have reinstalled and tested it. I works - thanks for your help. I will uninstall the old version form the main toolshed as both versions appear in the tool menu
