### ISSUE TITLE
LCA classifier fails with OSError

### ISSUE THREAD

**Issue by ehj000** [usegalaxy-no/galaxyadmin#20]
I have tested the tool LCA classifier with a valid input file, but get the following error:

Traceback (most recent call last):
  File "/srv/galaxy/var/shed_tools/galaxy-ntnu.bioinfo.no/toolshed_nels/repos/kjetil/lcaclassifier/25f531a37f53/lcaclassifier/LCAClassifier/LCAClassifier.py", line 55, in <module>
    LCAClassifier(arg[1], arg[2], arg[3], arg[4], arg[5], arg[6], arg[7])
  File "/srv/galaxy/var/shed_tools/galaxy-ntnu.bioinfo.no/toolshed_nels/repos/kjetil/lcaclassifier/25f531a37f53/lcaclassifier/LCAClassifier/LCAClassifier.py", line 13, in LCAClassifier
    f = open(path + '/LCAClassifier/lcaclassifier.conf', 'w')
OSError: [Errno 30] Read-only file system: '/srv/galaxy/var/shed_tools/galaxy-ntnu.bioinfo.no/toolshed_nels/repos/kjetil/lcaclassifier/25f531a37f53/lcaclassifier/LCAClassifier/LCAClassifier/lcaclassifier.conf'

**Comment by kjetilkl** [comment]
The tool attempts to create a configuration file located in the same directory as the tool itself, which is very unfortunate (and even write-protected in this case). Configuration files that are specific to each execution should always be written to the temporary job-execution directory.  

We will have to rewrite the tool itself to fix this.

**Comment by ehj000** [comment]
Ok, thanks for checking. This tools is part of an NeLS supported workflow, but I think we can wait until someone asks for this before we install it. Lots have happened in this field, and I am not sure this workflow is needed in the future
