### ISSUE TITLE
Metaphlan2 fails

### ISSUE THREAD

**Issue by ehj000** [usegalaxy-no/galaxyadmin#21]
I suspect this is because the database the tool use is downloaded first time the tool is used. Can someone with ssh access try to run this command to download the database:

metaphlan2.py --install

**Comment by torfinnnome** [comment]
It looks like the database is managed using a data manager:

From https://github.com/galaxyproject/tools-iuc/blob/master/tools/metaphlan2/repository_dependencies.xml:
"This requires the MetaPhlAn2 data manager definition to install all required databases."

**Comment by ehj000** [comment]
Ok, but using the data manager gives the following error:

/bin/sh: download_metaphlan2_db.py: command not found
Traceback (most recent call last):
  File "/srv/galaxy/var/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/data_manager_metaphlan2_database_downloader/9c4ad82be5bd/data_manager_metaphlan2_database_downloader/data_manager/data_manager_metaphlan2_download.py", line 144, in <module>
    target_dir)
  File "/srv/galaxy/var/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/data_manager_metaphlan2_database_downloader/9c4ad82be5bd/data_manager_metaphlan2_database_downloader/data_manager/data_manager_metaphlan2_download.py", line 99, in download_metaphlan2_db
    subprocess.check_call(cmd, shell=True)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'download_metaphlan2_db.py --output /srv/galaxy/jobs/005/5674/working/dataset_9058_files' returned non-zero exit status 127.

**Comment by torfinnnome** [comment]
Ok, will look into it.

**Comment by torfinnnome** [comment]
The requirement seems to be properly defined in the tool xml file, `/srv/galaxy/var/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/data_manager_metaphlan2_database_downloader/83f07f40b200/data_manager_metaphlan2_database_downloader/data_manager/data_manager_metaphlan2_download.xml`:

`        <requirement type="package" version="2.6.0">metaphlan2</requirement>`

However, when running the data manager, it is using the default Singularity container. And I really have no idea why. I will try to ask around.

**Comment by ehj000** [comment]
I am planning to use Metaphlan2 for to upcoming ELIXIR workshops. Any progress on troubleshooting why the data manager tool is failing? If not, I could try to install the database manually

**Comment by torfinnnome** [comment]
I was able to install the metaphlan2 database on prod now (I gave up - Galaxy is not ready for a Singularity-only setting, sigh). Could you test your tools/workflow?

**Comment by ehj000** [comment]
Looks like it finds the database, but throws another error:
WARNING:galaxy.model:Datatype class not found for extension 'biom'
In the Data type table, I find Biom1 and Biom2. Anyone that can instruct me how to add a new data type in usegalaxy?

**Comment by torfinnnome** [comment]
The metahplan2 tool xml from the tool-shed is not in sync with https://github.com/galaxyproject/tools-iuc/tree/master/tools/metaphlan2/. (Which is weird and annoying.) I have now installed the version from github, which should fix the biom dataclass issue.

However, I need to restart Galaxy in order to make it visible. Will restart when there is less traffic, some time later today.

**Comment by torfinnnome** [comment]
Seems to work now?
<img width="274" alt="Screenshot 2021-03-10 at 08 22 00" src="https://user-images.githubusercontent.com/985657/110591765-c02afa00-8179-11eb-9a53-7ca6f78cad52.png">
