### ISSUE TITLE
Set up Training Infrastructure as a Service (TIaaS)

### ISSUE THREAD

**Issue by torfinnnome** [usegalaxy-no/galaxyadmin#29]
Is this something we should offer in the long run?

https://training.galaxyproject.org/training-material/topics/admin/tutorials/tiaas/tutorial.html

**Comment by ehj000** [comment]
This looks very nice and could be a good extension of the training we provide, although I don't fully understand how this works. E.g. who will be the instructors, us (WP4). In that case we would need some training of the instructors. First up is to translate the existing training material (NeLS/galaxy) to online courses and start giving courses
