### ISSUE TITLE
Get files from NeLS storage (and Send files) missing after upgrade!

### ISSUE THREAD

**Issue by kjellp** [usegalaxy-no/galaxyadmin#30]
RT#14984 "However, I cannot find the “Get files from NeLS storage”- function anymore.. Is there any possibility to directly import files from the Nels storage into the usegalxy.no system?" 

Double checked and confirmed on usegalaxy.no (alsp Send data/files to NeLS is missing). Related to the upgrade and redeployment of the left tools panel?

**Comment by torfinnnome** [comment]
Sorry, fixed. (tool_config_file parameter in galaxy.yml was missing /srv/galaxy/server/config/nels_tool_conf.xml)
