### ISSUE TITLE
New usegalaxy web admin member

### ISSUE THREAD

**Issue by ehj000** [usegalaxy-no/galaxyadmin#32]
Kjersti Rise (kjersti.rise@ntnu.no) has joined this group. Could she be given web admin permissions. I would be happy to join a small 1-2-1 session when she is added - if this is a task for the usegalaxy admins and not the sysadmins

**Comment by torfinnnome** [comment]
Here's how to add a new Galaxy admin user: https://github.com/usegalaxy-no/galaxyadmin/wiki/How-to-grant-galaxy-admin-access

**Comment by ehj000** [comment]
Is this procedure also for adding usegalaxy web admin users? If yes, the @brugger and @torfinnnome: I need the Ansible vault password

**Comment by torfinnnome** [comment]
Sorry, it was supposed to say "Galaxy web admin user": I have updated the page. New link: https://github.com/usegalaxy-no/galaxyadmin/wiki/How-to-grant-galaxy-web-admin-access

**Comment by ehj000** [comment]
I have followed the excellent documentation on how to add new galaxy web admins, but the process fails at step 6 with the following error:
[WARNING]: While constructing a mapping from /Users/ehj000/prosjekter/infrastructure-playbook/env/test/group_vars/galaxy.yml, line 223, column 3, found a duplicate dict key
(services). Using last defined value only.
ERROR! the role 'geerlingguy.repo-epel' was not found in /Users/ehj000/prosjekter/infrastructure-playbook/env/test/roles:/Users/ehj000/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/Users/ehj000/prosjekter/infrastructure-playbook/env/test

The error appears to be in '/Users/ehj000/prosjekter/infrastructure-playbook/env/test/galaxy.yml': line 53, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - geerlingguy.repo-epel
      ^ here

Any ideas why?

**Comment by kjetilkl** [comment]
I encountered the same problem the first time I tried, and I solved it by installing the required roles again with the command:
`ansible-galaxy install -r requirements.yml`. I added this to the documentation, but when I tried to reproduce the error a second time with a clean clone of the repository, it worked without any problems. So, I assumed I just had a bit of bad luck the first time and removed this part from the documentation.

**Comment by ehj000** [comment]
Ok, thanks, but after a clean clone I encounter another error related to ssh connection:

TASK [Gathering Facts] ******************************************************************************************************************************************************
[WARNING]: Unhandled error in Python interpreter discovery for host test.usegalaxy.no: Failed to connect to the host via ssh: sysadmin@158.39.201.116: Permission denied
(publickey,gssapi-keyex,gssapi-with-mic).
fatal: [test.usegalaxy.no]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"158.39.201.116\". Make sure this host can be reached over ssh: sysadmin@158.39.201.116: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).\r\n", "unreachable": true}

PLAY RECAP ******************************************************************************************************************************************************************
test.usegalaxy.no          : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0

**Comment by torfinnnome** [comment]
Hm, right, you need to have your ssh key added to the sysadmin user in order to run the Playbooks.

**Comment by ehj000** [comment]
BTW: Does web admins need to registered a user on test NeLS in order to get access to test-usegalaxy. If yes, it can be added to the wiki documentation

**Comment by torfinnnome** [comment]
I think that's required today, yes. But there were some talk about switching to using the non-test NeLS version for test.usegalaxy.no as well? @kjellp?

**Comment by kjellp** [comment]
I also vaguely remember that being "aired" at some point, but don't 
think it has been fully discussed anywhere and concluded to my 
knowledge. And now I think the NeLS developers are relying on 
test.usegalaxy.no to be the "proper"/representative test instance 
towards NeLS regarding dataset and history transfers (NGA).

So for now I think we need to have a test account on test-NeLS for the 
web admins of test.usegalaxy.no, and should update the docs.

K.

**Comment by ehj000** [comment]
At the last step of granting web admin access, the git commit -m "Added new Galaxy web admin user" step throws an error:
git commit -m "Added new Galaxy web admin user"

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'ehj000@uit-mac-178.(none)')

I have not made any changes to the ./git/config file.

**Comment by torfinnnome** [comment]
@ehj000 Were you able to run the playbook?

**Comment by ehj000** [comment]
Unfortunately not. Running the galaxy.yml playbook throws an error I am not able to resolve:

$ ansible-playbook galaxy.yml
ERROR! couldn't resolve module/action 'firewalld'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/Users/ehj000/GitHub/usegalaxy-no/infrastructure-playbook/env/test/tasks/_firewall_trusted_network.yml': line 6, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


    - name: add firewalld rule for trusted network
      ^ here

I have asked Espen to try to add the two new web admins

**Comment by emrobe** [comment]
This should be resolved. I added Kjersti and Gareth a while back
