### ISSUE TITLE
Access to data.test.usegalaxy.no and data.usegalaxy.no

### ISSUE THREAD

**Issue by ehj000** [usegalaxy-no/galaxyadmin#33]
I have SSH access to test.usegalaxy.no and usegalaxy.no, but can't access data.test.usegalaxy.no and data.usegalaxy.no. Do I need extra permissions for this, and who can give me that?

**Comment by torfinnnome** [comment]
Only the sysadmin user have access to data.usegalaxy.no (aka db.usegalaxy.no). Not the galaxyadmin user.

**Comment by ehj000** [comment]
Ok, fine. But in order to add local reference data, you need to have access there - which means that this is a job for the sysadmins?

**Comment by torfinnnome** [comment]
Currently, yes. Probably something for the next "AOB". :)
