### ISSUE TITLE
Merge BAM Files fails: problems finding .jar file

### ISSUE THREAD

**Issue by ehj000** [usegalaxy-no/galaxyadmin#36]
A user reports that the tools fails with the following error: Error: Unable to access jarfile /MergeSamFiles.jar

I see from an old post in Biostar from Bjoern Gruening that "we are not allowed to ship the JAR file, because of licensing issues. You need to download it by yourself and specify the location in the env.sh file in you GATK Tool Shed installation directory." 

Although a different tool, could this be whats causing the problem?

**Comment by torfinnnome** [comment]
Can the "Samtools merge" tool be used?

(And if so; remove this non-functional tool.)

**Comment by ehj000** [comment]
Do you know if they give the same output? I have forwarded this suggestion to the user. Thanks

**Comment by kjetilkl** [comment]
The Picard requirement is installed from BioConda, and it includes the file "MergeSamFiles.jar". But the command-line in the wrapper specifies the path to this JAR file as "$JAVA_JAR_PATH/MergeSamFiles.jar" and the environment variable "$JAVA_JAR_PATH" is not set anywhere.

**Comment by torfinnnome** [comment]
Should we put these jar files on our CVMFS somewhere?

**Comment by torfinnnome** [comment]
Fixed: https://github.com/usegalaxy-no/infrastructure-playbook/commit/0d4e5fe3e17fbe7a31e8b35d86591bd5d4ec15ca
