### ISSUE TITLE
BamLeftAlign fails. 

### ISSUE THREAD

**Issue by ehj000** [usegalaxy-no/galaxyadmin#37]
A user reports that the tools fails with the following error: 
data/part0/tmp/jobs/015/15270/tool_script.sh: 9: /data/part0/tmp/jobs/015/15270/tool_script.sh: samtools: not found
/data/part0/tmp/jobs/015/15270/tool_script.sh: 9: /data/part0/tmp/jobs/015/15270/tool_script.sh: bamleftalign: not found

Both samtools and bamleftalign are installed, so I don't understand the error

**Comment by torfinnnome** [comment]
There seems to be two versions of bamleftalign installed.

This version works for me: toolshed.g2.bx.psu.edu/repos/devteam/freebayes/bamleftalign/1.3.1

Could you test?

**Comment by ehj000** [comment]
Yes, it works. Thank you
