### ISSUE TITLE
SnpSift Filter requires Java

### ISSUE THREAD

**Issue by kjetilkl** [usegalaxy-no/galaxyadmin#43]
A user has complained that the "SnpSift Filter" tool always fails. It seems to be because Java is missing.

`/data/part0/tmp/jobs/083/83088/tool_script.sh: 9: /data/part0/tmp/jobs/083/83088/tool_script.sh: java: not found`

Java is not specified as a requirement in the tool wrapper, but I though that Java was part of our base container image.

**Comment by torfinnnome** [comment]
The base image is only used for tools not having any requirements.

**Comment by kjetilkl** [comment]
So what is the best course of action in this case? Install Java on all compute nodes or rewrite the wrapper. Or is it possible to ban this particular tool from using the BioContainer container, so our server has to build a new one derived from our base image?

**Comment by torfinnnome** [comment]
Forcing tools to use conda doesn't seem to be possible (I asked a few months back), unfortunately. The snpSift biocontainer includes java, so why this happens is very strange and annoying. I would guess that adding `<requirement type="package" version="11.0.1">openjdk</requirement>` to the macros.xml would fix this issue (and restarting Galaxy). However, that's kind of an ugly hack, albeit quick.

I guess the best course of action is to make an issue to IUC and ask them (https://github.com/galaxyproject/tools-iuc).

**Comment by ehj000** [comment]
Can add to this that the user has tested the same tool with the same input data in usegalaxy.eu with success

**Comment by ehj000** [comment]
Should we go for the ugly hack and help the end user?

**Comment by torfinnnome** [comment]
Could one of you try it? So more people are familiar with doing these kinds of modifications. `/srv/galaxy/var/shed_tools/` is the root directory for the tool repositories.

**Comment by kjetilkl** [comment]
I tried to add the "openjdk" requirement to the tool wrapper on the test server. It failed before and after, but I did not see the "java: not found" error (neither before nor after), so it may have failed for a different reason. According to the log, it did try to build a container that included Java.

**Comment by torfinnnome** [comment]
Hm. Building the mulled container fails. Weird. Could you try to update the wrapper on prod?

**Comment by kjetilkl** [comment]
I have updated the wrapper in prod (version "4.3+t.galaxy1"), but I have not restarted Galaxy

**Comment by torfinnnome** [comment]
Just restarted Galaxy. And now the container was successfully built. Seems like the tool works now?

**Comment by ehj000** [comment]
Thanks, but according to the user the tool fails with the same error:

Fatal error: Exit code 127 (Error)

Tool generated the following standard error:

/data/part0/tmp/jobs/084/84956/tool_script.sh: 9: /data/part0/tmp/jobs/084/84956/tool_script.sh: java: not found

**Comment by torfinnnome** [comment]
Ok, there seems to be two versions of "snpSift filter".
iuc/snpeff/snpSift_filter/3.4 and iuc/snpsift/snpSift_filter/4.3+t.galaxy1

4.3+t.galaxy1 seems to work (for me, at least). Should we remove the snpeff/snpSift version(s)?

**Comment by ehj000** [comment]
That resolved the issue. Thank you Torfinn, and yes we should delete the iuc/snpeff/snpSift_filter/3.4 since it is not working
