### ISSUE TITLE
Java error: cannot open shared object file

### ISSUE THREAD

**Issue by ehj000** [usegalaxy-no/galaxyadmin#48]
The tool Trimmomatic fails with the following error:
java: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
Could someone please have a look why the file is not accessible? The tool is going to be used on the IBA workshop, so it is urgent

**Comment by kjetilkl** [comment]
I deleted the "mulled-v2-e1a6ade46756da3bd8ceef31e6d2e7645f383a87:5cea15127895d50e80d4a0350938adabaf77375e-0" container and ran a Trimmomatic job to force a rebuild. The size of the new container is 259MB compared to 231MB before. That seems to have solved the problem.

**Comment by ehj000** [comment]
Trimmomatic works fine now. Thanks
