### ISSUE TITLE
Cluster error

### ISSUE THREAD

**Issue by ehj000** [usegalaxy-no/galaxyadmin#54]
A user is reporting that the tool Trinity (de novo assembly) is failing with this error: Unable to run this job due to a cluster error, please retry it later

He also reports that the tool runs on usegalaxy.eu

I am able to reproduce the error on usegalaxy, but need a sysadmin to look at this

**Comment by torfinnnome** [comment]
NREC is currently down for maintenance. And for some reason the slurm.usegalaxy.no was also down (will try to figure out why). I re-enabled slurm.usegalaxy.no, and jobs should be running again now.

**Comment by torfinnnome** [comment]
Fixed: https://github.com/usegalaxy-no/infrastructure-playbook/commit/b5dc2cc013a7c1d6603495ad5ddb7438c9ea1db8
