### ISSUE TITLE
CD-Hit EST tool error

### ISSUE THREAD

**Issue by tothuhien** [usegalaxy-no/galaxyadmin#56]
A user reported that the tool CD-Hit EST failed to run. There're 2 versions of it on usegalaxy.no, 

one failed with the error: 
/data/part0/tmp/jobs/000/114/114281/tool_script.sh: 9: /data/part0/tmp/jobs/000/114/114281/tool_script.sh: cd-hit-est: not found

the other failed with the error:
cd-hit-est: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory

**Comment by torfinnnome** [comment]
Both are old tools not using Conda, but rather tries to download the source code and compile it. Not compatible with usegalaxy.no.

**Comment by ehj000** [comment]
Thanks Torfinn. I have installed and tested a more recent version of CD-HIT (4.6.8.1 ) that seem to work fine. Will communicate this to the user
