### ISSUE TITLE
Plotting tool fails

### ISSUE THREAD

**Issue by ehj000** [usegalaxy-no/galaxyadmin#57]
The tool fail with the following error: 'R' is required by this tool but was not found on path
Could someone with permission please check why R is not available to the tool?

**Comment by kjetilkl** [comment]
The tool was installed in 3 revisions (one for v1.0.1 and two for v1.0.2), all with different requirements which may have been missing. I removed 2 of these and believe the remaining version 1.0.2 that only requires "r-base=3.4.2" should work. At least R was working inside this container when I tested manually.

**Comment by ehj000** [comment]
Thanks Kjetil. This version of the tool is working as expected.
