### ISSUE TITLE
R not found

### ISSUE THREAD

**Issue by ehj000** [usegalaxy-no/galaxyadmin#60]
The tool T Test for Two Samples fail with this error: sh: 1: R: not found
Could someone have a look why it is not able to find R? It is a bit urgent for the NMBU course...

**Comment by kjetilkl** [comment]
I made a new Singularity container with R=3.1.2 and perl=5.26.2 and called it "r:2.11.0" so that I did not have to change the original tool wrapper. It worked on the test datasets that came with the wrapper.
