### ISSUE TITLE
ParSNP No space left on device

### ISSUE THREAD

**Issue by ehj000** [usegalaxy-no/galaxyadmin#61]
A user report that the tool ParSNP fails with the following error:

FATAL:   Unable to handle docker://quay.io/biocontainers/parsnp:1.2--h1341992_0 uri: while building SIF from layers: while creating squashfs: create command failed: exit status 1: 
Write failed because No space left on device

FATAL ERROR:Failed to write to output filesystem

None of the disks on the system seems full, however I am not sure where the container is trying to build

**Comment by kjellp** [comment]
@kjetilkl this sounds very familiar to earlier tools container building trouble? Tried to have a quick look in the "How to debug a tool that has failed" troubleshooting document linked from the wiki, but did not find the exact same problem described there, but I'm, pretty sure we've seen the exact same messages before.

**Comment by kjetilkl** [comment]
The same error was mentioned in our "usegalaxy" Slack channel on April 26th, 2021. Torfinn fixed it, but he did not document how
