### ISSUE TITLE
Jbrowse in usegalaxy

### ISSUE THREAD

**Issue by ehj000** [usegalaxy-no/galaxyadmin#64]
A user is not able to visualize data using Jbrowse. The problem is reproducible. Has anyone been able to visualize data with jbrowse in usegalaxy.no?

JBrowse window.onerror=function(msg){ if( document.body ) document.body.setAttribute("JSError",msg); } if(window.process&&process.versions&&process.versions.electron) { window.electronRequire = require; delete window.require; } html, body, div.jbrowse { margin: 0; padding: 0; height: 100%; width: 100%; }
Loading...
JBrowseDefaultMainPage

**Comment by kjetilkl** [comment]
It could be because the JBrowse tool was not added to the "allowlist" which allows it to display unsanitized HTML. I have added it now, and I am able to see the genome browser

**Comment by kjetilkl** [comment]
Although sometimes I still get the same error, but when I reload the page it suddenly works again...

**Comment by ehj000** [comment]
I think I did add it to the allow list before testing, but it works now when reloading. Thank you Kjetil

**Comment by sveinugu** [comment]
> Although sometimes I still get the same error, but when I reload the page in the middle frame it suddenly works again...

Autoupdates of config while a server is running is not managed properly when there are more than one web server process running (at least this used to be the case). Reloading the web browser might connect to another web server which has not loaded new configs, hence such strange behaviour. A full restart should fix the issue.

**Comment by tothuhien** [comment]
I have the same problem now, and it does not work when I reload the page.
By the way, is there any other alternative? IGV seems to not working neither.

**Comment by kjetilkl** [comment]
JBrowse version 1.16.11 had not yet been whitelisted, only 1.16.10 and 1.16.9. 
See if it works now.

**Comment by tothuhien** [comment]
awesome! Thanks.
