### ISSUE TITLE
Trim Galore! failures

### ISSUE THREAD

**Issue by kareadlikeabook** [usegalaxy-no/galaxyadmin#68]
Trim Galore has had issues with some, but not all, similar datafiles with the following error message:

"FATAL:   could not open image /cvmfs/singularity.galaxyproject.org/all/trim-galore:0.6.7--hdfd78af_0: image format not recognized".

I am new to Galaxy/Trim Galore! but would appreciate insight as this has not been an issue across all of my files from recent sequencing.

Thank you!

**Comment by kjetilkl** [comment]
We have not been able to reproduce this problem on our server and could not find your error message in our logs. 

Are you sure this error is affecting the Norwegian Galaxy server [UseGalaxy.no](https://usegalaxy.no/) and not some other server, like [UseGalaxy.org](https://usegalaxy.org/) or [UseGalaxy.eu](https://usegalaxy.eu/)?

**Comment by kareadlikeabook** [comment]
> We have not been able to reproduce this problem on our server and could not find your error message in our logs.
> 
> Are you sure this error is affecting the Norwegian Galaxy server [UseGalaxy.no](https://usegalaxy.no/) and not some other server, like [UseGalaxy.org](https://usegalaxy.org/) or [UseGalaxy.eu](https://usegalaxy.eu/)?

Thank you so much for your follow up; apologies, this is on the UseGalaxy.org server. I will repost there.
