### ISSUE TITLE
running in parallel for repeatmasker

### ISSUE THREAD

**Issue by tothuhien** [usegalaxy-no/galaxyadmin#70]
The tool [RepeatMasker ](https://usegalaxy.no/root?tool_id=toolshed.g2.bx.psu.edu/repos/bgruening/repeat_masker/repeatmasker_wrapper/4.1.1) has a parallel option which is set as:
`-parallel \${GALAXY_SLOTS:-1}`

but it always run with 1 cpu. Is it something to do with the tool_destinations.yaml file? Thanks.

**Comment by tothuhien** [comment]
Great, thanks Kjetil!

**Comment by kjetilkl** [comment]
I did not see your pull request @tothuhien before now, so I hadn't noticed that you had solved the problem already long before me! :-)

**Comment by tothuhien** [comment]
haha, as long as it was fixed :-)
