### ISSUE TITLE
slurm jobs stuck in CG state

### ISSUE THREAD

**Issue by tothuhien** [usegalaxy-no/galaxyadmin#74]
Some slurm jobs have finished or were deleted by user but still in CG state of the slurm queue.

**Comment by kjetilkl** [comment]
I tried restarting `slurmctld` on the main node and `slurmd` on `slurm.usegalaxy.no`. That did not fix things, but sometime later the `slurm.usegalaxy.no` node went down for some reason, and that seems to have cleared up the CG jobs, which had all been running on this node.

**Comment by kjetilkl** [comment]
The `slurm.usegalaxy.no` node is "not responding" at the moment, however

**Comment by kjellp** [comment]
The slurm.usegalaxy.no host is answering to ping from usegalaxy.no (logged in as galaxyadmin).

I also tried ssh into slurm.usegalaxy.no, and the ssh prompt responded immediately, so it seems like the slurm.usegalaxy.no node is responsive now?

Are there still issues, and do we need to assistance from Stanislav that have access to server from the hypervisor side?

K.
________________________________

**Comment by kjetilkl** [comment]
Yes, everything seems to be in order with `slurm.usegalaxy.no`, but it still has an asterisk behind the node state reported by `sinfo`, which means that it is not responding. Assistance from someone with better Slurm skills would be nice!

**Comment by sveinugu** [comment]
> Assistance from someone with better Slurm skills would be nice!

So who would that be? @emrobe? If I remember correctly, @nemyxun was also supposed to increase his slurm skills. How urgent is this?

**Comment by nemyxun** [comment]
Hello All,

@sveinugu Sveinung, I have SU access on host test.usegalaxy.no only by SSH key..

**Comment by kjellp** [comment]
Dont forget that Teshome from NMBU has joined, and is maybe able to help on slurm matters. And probably not seeing these messages!

**Comment by kjetilkl** [comment]
I have restored sysadmin access to the production stack for Lev, Sveinung and Hien. I had probably just hacked the _authorized_keys_ file last time and forgot to do it properly via the playbooks, so it was overwritten again during summer

**Comment by sveinugu** [comment]
> Dont forget that Teshome from NMBU has joined, and is maybe able to help on slurm matters. And probably not seeing these messages!

@teshomem?

**Comment by teshomem** [comment]
CG state means the node that runs the job is not responding. You can't even SSH to the node in many cases. The solution that worked form is first to restart the node and restart the slurmd on the node. The (*) indicates that the node is unreachable. This happens when the slurmd daemon isn't started.

**Comment by emrobe** [comment]
I've just checked and restarted all services involved. This seems to be something else.

**scontrol: error: slurm_slurmd_info: Connection refused**

**Comment by teshomem** [comment]
If you are using Munge, make sure it is started. Otherwise, share the slurmctld log on the slurmctld server.

**Comment by emrobe** [comment]
Slurmctld is filled with these:
**[2022-08-26T13:36:17.521] error: Nodes ecc3.usegalaxy.no not responding
[2022-08-26T13:38:01.718] error: Node ecc1.usegalaxy.no appears to have a different slurm.conf than the slurmctld.  This could cause issues with communication and functionality.  Please review both files and make sure they are the same.  If this is expected ignore, and set DebugFlags=NO_CONF_HASH in your slurm.conf.
[2022-08-26T13:38:01.718] error: Node nrec2.usegalaxy.no appears to have a different slurm.conf than the slurmctld.  This could cause issues with communication and functionality.  Please review both files and make sure they are the same.  If this is expected ignore, and set DebugFlags=NO_CONF_HASH in your slurm.conf.
[2022-08-26T13:38:01.720] error: Node ecc2.usegalaxy.no appears to have a different slurm.conf than the slurmctld.  This could cause issues with communication and functionality.  Please review both files and make sure they are the same.  If this is expected ignore, and set DebugFlags=NO_CONF_HASH in your slurm.conf.
[2022-08-26T13:41:17.003] error: Nodes ecc3.usegalaxy.no not responding**

... and I am 90 % sure it stems from the fact that ecc somehow behaves in a non-deterministic fashion which screws up the various .conf files involved on the slurm nodes as it adds/removes nodes. We should make fixing/looking into this this a priority. (Or even consider whether we need this extra layer of complexity in our system)

**Comment by teshomem** [comment]
From the log file, i am kind of sure that the slurm.conf isnt in sync between slurm deamon and the node. That explains why the slurmd daemon cannot connect to the node. This can be solved by using a shared file in a shared file system.
