### ISSUE TITLE
Stabilize usegalaxy <-> NeLS dataset transfers

### ISSUE THREAD

**Issue by kjellp** [usegalaxy-no/galaxyadmin#9]
Some times issues with users being detected as logged out of galaxy session in when beeing re-directed back to galaxy from NeLS, When this happens, the initation of the transfer fails and user is left with nothing happening in the galaxy interface, and needs to try again.

**Comment by bruggerk** [comment]
Had a dig around and it looks like a general problem and not isolated to the nels transfer tools

I used the: Get Data -> UCSC Archaes table browser

Has anyone checked with the community if this is only experienced by us or by others as well?

/kim

**Comment by kjellp** [comment]
@torfinnnome  and I did some testing Wed-Friday, turning the number of uwsgi threads down from 4 to 1. Then the error disappeared, and it did not reappear when no of threads was reset again to 4 on Friday. 
I tried to re-create the error @bruggerk mentioned (Get Data -> UCSC Archaes table browser), but the re-direction worked nicely there today (will try a bit more extensively). Have not heard others reporting similar trouble, and couldn't find any mention when googling a bit.

**Comment by bruggerk** [comment]
On Mon, 2020-12-07 at 00:25 -0800, Kjell Petersen wrote:
> @torfinnnome  and I did some testing Wed-Friday, turning the number
> of uwsgi threads down from 4 to 1. Then the error disappeared, and it
> did not reappear when no of threads was reset again to 4 on Friday.

By limiting the number of threads to 1 we lose all parallelism -->
longer load times.

> I tried to re-create the error @bruggerk mentioned (Get Data -> UCSC
> Archaes table browser), but the re-direction worked nicely there
> today (will try a bit more extensively). Have not heard others
> reporting similar trouble, and couldn't find any mention when
> googling a bit.

Was this using the test or prod server? I used the test one. Just to
clarify is this a problem on both the test and prod server or just the
test one?

**Comment by bruggerk** [comment]
just tried the archea import on prod and it locks me out.
/Kim

**Comment by kjellp** [comment]
All tests are done using test.usegalaxy.no (but the error was verified on both test and prod 5 days ago).

I just tried "Get Data -> Main UCSC", and got logged out 2 out of ~8 times... So it's still there. Not possible to test "Send/Get to/from NeLS" as the nels test stack currenly gives (401 - Unauthorized on all files and folders after login).

**Comment by bruggerk** [comment]
It was resat after a redeployment of the sites this morning, but works
with prod (both history in/ex-port and normal im/ex-port.Plus it is
back running  with 4 threads.
/Kim

**Comment by kjellp** [comment]
> It was resat after a redeployment of the sites this morning, but works with prod (both history in/ex-port and normal im/ex-port.Plus it is back running with 4 threads. /Kim

Sorry don't follow now, what was reset? The test.usegalaxy.no server? (or test nels (or nga)). I'm having 7 hanging import jobs on test.usegalaxy.no and can not see any files/folder content in test nels due to 401 (could be user specific error).

I noticed test.usegalaxy.no was connected to prod nels for a short period, so I assume you refer to that transfers were working as expected then?

K.

> […](#)
> On Mon, 2020-12-07 at 00:37 -0800, Kjell Petersen wrote: All tests are done using test.usegalaxy.no (but the error was verified on both test and prod 5 days ago). I just tried "Get Data -> Main UCSC", and got logged out 2 out of ~8 times... So it's still there. Not possible to test "Send/Get to/from NeLS" as the nels test stack currenly gives (401 - Unauthorized on all files and folders after login). — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by bruggerk** [comment]
Yes the test.usegalaxy.no was redeployed, prior to that the
test.usegalaxy.no used the prod-NeLS setup for testing for both types
of imports/exports as the  test-NeLS is broken.
What kind of imports are we talking about and on what server? I assume
general NeLS transfers as I cannot see anything hanging in any of the
NGA instances.

**Comment by kjellp** [comment]
> Yes the test.usegalaxy.no was redeployed, prior to that the test.usegalaxy.no used the prod-NeLS setup for testing for both types of imports/exports as the test-NeLS is broken. What kind of imports are we talking about and on what server? I assume general NeLS transfers as I cannot see anything hanging in any of the NGA instances.

They are Get Data -> UCSC (Main or Arhcea) import jobs that have been successfully initiated (successfully redirecting back to galaxy) but not started after being queued.

**Comment by bruggerk** [comment]
Loads of digging and debugging around, I think this might be the source of the problem:

![image](https://user-images.githubusercontent.com/13271096/101348394-db8d1d00-388b-11eb-964c-07a4b11b8db8.png)


Not sure how to fix it, but believe it is around here:
```/srv/galaxy/server/lib/galaxy/web/framework/webapp.py```

Will keep digging

**Comment by bruggerk** [comment]
Some serious hacking of std python libraries reveal that this was not the case, setting SameSite = Lax for the cookie does not change anything, but remove a warning or two.

**Comment by bruggerk** [comment]
I have debugged and tracked my way through the failing transfers and it originates from uwsgi and not in the galaxy code. Currently it fails in 1 out of 6 imports regardless the number of processes/threads used (within a reasonable sampling space).

I suggest talking to the community regarding this unless someone wants to do the uwsgi bit

**Comment by kjellp** [comment]
We discussed in the GalaxyAdmin group to post a request in the gitter channel, after testing if the bug is reproduced on usegalaxy.eu/org as well. Not been able to test or post yet.

**Comment by kjellp** [comment]
Not able to reproduce in usegalaxy.no (prod) now. But is present every time in test.usegalaxy.no, consistently across any remote data service : NeLS, UCSC Main, others). Post back URLs are being redirected to the login page instead of starting an import job in the active session.

**Comment by kjetilkl** [comment]
I'm closing this issue since this functionality is now covered by the NeLS remote storage plugin and the old tools have been deprecated
